import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import mongoose, { HydratedDocument } from 'mongoose';

import { Product } from '../products/products.schema';
import { User } from '../users/users.schema';

// ============================================================
// CART ITEM INTERFACE
// Defines the shape of each item inside the cartItems array.
// Using a proper interface removes ALL the @ts-ignore comments
// that were scattered across the service file.
// ============================================================
export interface CartItem {
  _id?: mongoose.Types.ObjectId; // auto-generated by MongoDB for each item
  product: mongoose.Types.ObjectId; // reference to the Product document
  color: string;                // selected color variant
  quantity: number;             // how many of this product
  price: number;                // price at the time it was added to cart
}

// ============================================================
// CART DOCUMENT TYPE
// HydratedDocument<Cart> adds Mongoose instance methods like
// .save(), .populate() etc. to the Cart class
// ============================================================
export type CartDocument = HydratedDocument<Cart>;

// ============================================================
// CART SCHEMA
// Each user has ONE cart document.
// The cart contains an array of cartItems (embedded documents).
// timestamps: true → adds createdAt and updatedAt automatically
// ============================================================
@Schema({ timestamps: true })
export class Cart {

  // ----------------------------------------------------------
  // CART ITEMS – array of embedded product items
  // Each item stores: product ref, color, quantity, price
  //
  // We store price in the cart item (not just reference the product)
  // because product prices can change — we want to lock in the
  // price at the time the user added it to their cart
  // ----------------------------------------------------------
  @Prop({
    type: [
      {
        product: {
          type: mongoose.Schema.Types.ObjectId,
          ref: Product.name,
          required: true,
        },
        color: {
          type: String,
          default: '',
        },
        quantity: {
          type: Number,
          default: 1,
          min: [1, 'Quantity must be at least 1'],
        },
        price: {
          type: Number,
          required: true,
          min: [0, 'Price cannot be negative'],
        },
      },
    ],
    default: [],
  })
  cartItems: CartItem[]; 

  // ----------------------------------------------------------
  // TOTAL CART PRICE
  // Sum of (price × quantity) for all cart items
  // Recalculated every time the cart is modified
  // ----------------------------------------------------------
  @Prop({ type: Number, default: 0 })
  totalCartPrice: number;

  // ----------------------------------------------------------
  // TOTAL PRICE AFTER DISCOUNT
  // Only set when a valid coupon is applied
  // If no coupon → this field is not set / undefined
  // ----------------------------------------------------------
  @Prop({ type: Number })
  totalPriceAfterDiscount: number;

  // ----------------------------------------------------------
  // USER – reference to the User who owns this cart
  // Each user can only have ONE active cart at a time
  // ----------------------------------------------------------
  @Prop({
    type: mongoose.Schema.Types.ObjectId,
    ref: User.name,
    required: true,
    unique: true, // one cart per user
  })
  user: mongoose.Types.ObjectId;
}

export const CartSchema = SchemaFactory.createForClass(Cart);